version: '3.6'
volumes:
  node-modules:
    driver: local
services:
  app:
    build: 
      context: ./app
      dockerfile: dev.Dockerfile
    environment:
      - NODE_ENV=development
    command: 'ng serve --host 0.0.0.0 --poll=500 --port 4201'
    ports:
      - '4201:4201' 
      - '49153:49153'
    volumes:
      - node-modules:/usr/app/node_modules
      - ./app/:/usr/app/
